apiVersion: v1
kind: Service
metadata:
  name: sample-2
  labels:
    app: sample-2
spec:
  type: ClusterIP
  selector:
    app: sample-2
  ports:
    - name: http
      port: 80
      targetPort: 3000
