apiVersion: v1
kind: Pod
metadata:
  name: downwardapi-demo
  labels:
    app: down
    env: test
  annotations:
    owner: farooq
spec:
  containers:
  - name: demo
    image: busybox
    command: ["sh", "-c"]
    args:
    - |
      echo "Starting..."; 
      while true; do 
        echo "---- LABELS ----"; cat /etc/podinfo/labels;
        echo "---- ANNOTATIONS ----"; cat /etc/podinfo/annotations;
        sleep 5;
      done
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: "labels"
        fieldRef:
          fieldPath: metadata.labels
      - path: "annotations"
        fieldRef:
          fieldPath: metadata.annotations
