apiVersion: v1
kind: Service
metadata:
  name: backend-clusterip
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8080          # Service port inside cluster
      targetPort: 80      # Container port (inside Pod)
  type: ClusterIP
