apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - name: http
      port: 8080           # LoadBalancer port
      targetPort: 80       # Container port
