apiVersion: v1
kind: Service
metadata:
  name: frontend-nodeport
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - name: web
      port: 8080           # Service port inside cluster
      targetPort: 80       # Container port (inside Pod)
      nodePort: 31080      # External access port
