apiVersion: v1
kind: Service
metadata:
  name: web-svc
  labels:
    app: web
spec:
  clusterIP: None          # <--- Headless service
  selector:
    app: web
  ports:
    - name: http
      port: 80
      targetPort: 80
