apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "dummy-svc"   # required field, but service not used in Lab 1
  replicas: 3
  selector:
    matchLabels:
      app: web
  podManagementPolicy: OrderedReady   # start pods in order: web-0, web-1, web-2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
