# -------------------------------
# 1️⃣  Self-signed Issuer
# -------------------------------
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}

---
# -------------------------------
# 2️⃣  Certificate (Self-signed)
# -------------------------------
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-secret
  namespace: default
spec:
  secretName: tls-secret
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  dnsNames:
    - devopsdummies.com
    - sample-3.devopsdummies.com
    - sample-4.devopsdummies.com

---

