apiVersion: v1
kind: Pod
metadata:
  name: downwardapi-volume
  labels:
    dapi: volume
    cluster: test-cluster
  annotations:
    color: red
spec:
  containers:
    - name: client-container
      image: busybox
      command: ["sh", "-c"]
      args:
        - |
          while true; do
            echo "----- LABELS -----"
            cat /etc/podinfo/labels
            echo "----- ANNOTATIONS -----"
            cat /etc/podinfo/annotations
            sleep 5
          done
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
